### ISSUE TITLE
Difference between the Mac and Linux version

### ISSUE THREAD

**Issue by EHadoux** [guillaume-bosc/BalanceSpan#1]
Hi, after a quick look I could not find any difference in the sources between the Mac and the Linux version. Can you point them out please?

Cheers

**Comment by guillaume-bosc** [comment]
Hi,

Effectively, you are right, there is little difference between the Mac and the Linux version.
Only some data structures differ: In the file ClosedTree.h (within the SeqTree folder), we used unordered_map instead of hash_map.

Please, if you have any concerns, do not hesitate to contact me.

Cheers

**Comment by EHadoux** [comment]
Oh okay I see. What is the reason for that?
I was hoping to make a pull request with a cmakefile and a unified code base.

**Comment by mehdi-kaytoue** [comment]
You mean, we could simply use things like http://stackoverflow.com/questions/5919996/how-to-detect-reliably-mac-os-x-ios-linux-windows-in-c-preprocessor ?

**Comment by EHadoux** [comment]
Yes, or even better, just put the `--std=cxx14` flag and it should work with unordered_map (given that it's the one you want to use) for both versions (so only one would be needed).

**Comment by EHadoux** [comment]
I'll only use the Linux version I guess as I am putting everything on Docker.
